package com.amv.iestr.brainapp

const val RESULTADO = "resultado"

// Valores Por Defecto
const val N_PREGUNTAS: Int = 10
const val TIEMPO_PREGUNTA_SEG: Int = 5
const val NUMERO_MAX: Int = 99

var nPreguntas: Int = N_PREGUNTAS
var tiempoPregunta: Int = TIEMPO_PREGUNTA_SEG
var numeroMax: Int = NUMERO_MAX

// Batería con 200 preguntas
val preguntas = arrayOf(
    Pregunta("El signo zodiacal Acuario está representado por un tigre.", false),
    Pregunta("Marrakech es la capital de Marruecos.", false),
    Pregunta("Mónaco es el país más pequeño del mundo.", false),
    Pregunta("Hay cinco grupos sanguíneos diferentes.", false),
    Pregunta("Alexander Fleming descubrió la penicilina.", true),
    Pregunta("El intestino delgado mide unas tres veces y media la longitud de tu cuerpo.", true),
    Pregunta("Un pulpo tiene tres corazones.", true),
    Pregunta("Thomas Edison descubrió la gravedad.", false),
    Pregunta("Los cinco anillos de la bandera olímpica están entrelazados.", true),
    Pregunta("Los peces no pueden parpadear.", true),
    Pregunta("En el teclado, al lado de la letra Ñ se encuentra la letra K.", false),
    Pregunta("Todos los animales invertebrados son ovíparos.", true),
    Pregunta("Homero escribió 'La Odisea'.", true),
    Pregunta("Los delfines son mamíferos.", true),
    Pregunta("La casa de Ana Frank está en Berlín.", false),
    Pregunta("El elefante es el animal más grande del mundo.", false),
    Pregunta("Goya pintó 'Las Meninas'.", false),
    Pregunta("Colón descubrió América en 1492.", true),
    Pregunta("Mozart era alemán.", false),
    Pregunta("El idioma más antiguo de Europa es el vasco.", true),
    Pregunta("El desastre de Chernobyl ocurrió en 1986.", true),
    Pregunta("La segunda montaña más alta del mundo es el K2.", true),
    Pregunta("El guepardo es el animal más rápido del mundo.", true),
    Pregunta("El corazón tiene cuatro válvulas.", true),
    Pregunta("Neil Armstrong fue el primer hombre que pisó la Luna.", true),
    Pregunta("El Océano Atlántico es el más grande del mundo.", false),
    Pregunta("El hígado produce la insulina.", false),
    Pregunta("La libra es la moneda del Reino Unido.", true),
    Pregunta("Alemania fue ganadora del mundial de Brasil en 2014.", true),
    Pregunta("La Gran Muralla China es visible desde el espacio.", false),
    Pregunta("El sol es una estrella.", true),
    Pregunta("Los humanos tienen 46 cromosomas.", true),
    Pregunta("El Amazonas es el río más largo del mundo.", false),
    Pregunta("La teoría de la relatividad fue desarrollada por Isaac Newton.", false),
    Pregunta("La capital de Australia es Sydney.", false),
    Pregunta("El animal más pequeño del mundo es el colibrí.", false),
    Pregunta("El Monte Everest es la montaña más alta del mundo.", true),
    Pregunta("El Vaticano es un país independiente.", true),
    Pregunta("Las ballenas son mamíferos.", true),
    Pregunta("La luz viaja más rápido que el sonido.", true),
    Pregunta("La luna es el satélite natural de la Tierra.", true),
    Pregunta("El agua hierve a 100 grados Celsius a nivel del mar.", true),
    Pregunta("El polo norte es más frío que el polo sur.", false),
    Pregunta("Las cebras son blancas con rayas negras.", false),
    Pregunta("Los tigres son herbívoros.", false),
    Pregunta("El Everest está en Nepal.", true),
    Pregunta("Los diamantes son más duros que el acero.", true),
    Pregunta("Las arañas son insectos.", false),
    Pregunta("La bandera de Japón tiene un círculo rojo en el centro.", true),
    Pregunta("El ADN se encuentra en el núcleo de las células.", true),
    Pregunta("La electricidad fluye en circuitos cerrados.", true),
    Pregunta("Las abejas mueren cuando pican.", true),
    Pregunta("La Tierra es plana.", false),
    Pregunta("Los pinguinos viven en el norte del planeta.", false),
    Pregunta("Las jirafas son animales muy pequeños.", false),
    Pregunta("El agua es un líquido a temperatura ambiente.", true),
    Pregunta("El oro es un metal muy valioso.", true),
    Pregunta("El sol es una fuente de energía renovable.", true),
    Pregunta("Las serpientes tienen patas.", false),
    Pregunta("El Polo Sur está en el continente antártico.", true),
    Pregunta("Albert Einstein fue un científico que desarrolló la teoría de la gravedad.", false),
    Pregunta("La Luna es más grande que la Tierra.", false),
    Pregunta("Los pianos tienen 88 teclas.", true),
    Pregunta("Las tortugas pueden vivir más de 100 años.", true),
    Pregunta("El cuerno de un rinoceronte está hecho de hueso.", false),
    Pregunta("El cerebro humano tiene la misma capacidad que una computadora moderna.", false),
    Pregunta("El ajedrez es un juego que se juega en un tablero de 8x8.", true),
    Pregunta("El koala es un animal nativo de Australia.", true),
    Pregunta("La capital de Italia es Roma.", true),
    Pregunta("El hierro es un elemento químico.", true),
    Pregunta("Los humanos pueden respirar bajo el agua sin ayuda.", false),
    Pregunta("El Everest es más alto que el K2.", true),
    Pregunta("Los camellos tienen tres jorobas.", false),
    Pregunta("La órbita de la Tierra alrededor del Sol es circular.", false),
    Pregunta("El plomo es más pesado que el aluminio.", true),
    Pregunta("La mitocondria es conocida como la 'fábrica de energía' de la célula.", true),
    Pregunta("La Gran Barrera de Coral se encuentra en el océano Atlántico.", false),
    Pregunta("La piel es el órgano más grande del cuerpo humano.", true),
    Pregunta("La velocidad de la luz es menor que la del sonido.", false),
    Pregunta("El alcohol etílico es lo mismo que el metanol.", false),
    Pregunta("Los gatos son animales carnívoros.", true),
    Pregunta("El polo norte tiene más tierra que el polo sur.", false),
    Pregunta("El hielo flota porque es menos denso que el agua líquida.", true),
    Pregunta("El idioma oficial de Brasil es el español.", false),
    Pregunta("La bandera de México tiene un águila en el centro.", true),
    Pregunta("El tiburón es un pez.", true),
    Pregunta("Las estrellas fugaces son meteoros.", true),
    Pregunta("El chocolate se obtiene del cacao.", true),
    Pregunta("El cometa Halley pasa cerca de la Tierra cada 10 años.", false),
    Pregunta("La Mona Lisa fue pintada por Leonardo da Vinci.", true),
    Pregunta("El oro tiene un símbolo químico Au.", true),
    Pregunta("El panda gigante es nativo de América del Norte.", false),
    Pregunta("Las plantas convierten el dióxido de carbono en oxígeno.", true),
    Pregunta("El arcoíris tiene ocho colores.", false),
    Pregunta("La trompa de un elefante es una extensión de su nariz.", true),
    Pregunta("El ajedrez tiene piezas llamadas reyes y peones.", true),
    Pregunta("El agua salada es potable sin tratamiento.", false),
    Pregunta("La distancia entre la Tierra y el Sol es de unos 93 millones de millas.", true),
    Pregunta("El maíz es un cereal.", true),
    Pregunta("El pez payaso vive en simbiosis con anémonas.", true),
    Pregunta("El gato tiene cinco dedos en cada pata trasera.", false),
    Pregunta("El ser humano tiene cinco sentidos básicos.", true),
    Pregunta("La Tierra tiene forma esférica perfecta.", false),
    Pregunta("La bandera de Francia tiene tres colores.", true),
    Pregunta("Los lobos son herbívoros.", false),
    Pregunta("El ADN tiene forma de doble hélice.", true),
    Pregunta("Las hormigas tienen pulmones.", false),
    Pregunta("El piano es un instrumento de cuerda y percusión.", true),
    Pregunta("Los canguros llevan a sus crías en una bolsa llamada marsupio.", true),
    Pregunta("Los delfines respiran por branquias.", false),
    Pregunta("El planeta más grande del sistema solar es Saturno.", false),
    Pregunta("El nitrógeno es el gas más abundante en la atmósfera terrestre.", true),
    Pregunta("El arco de Triunfo está en Londres.", false),
    Pregunta("El ser humano necesita vitamina C para sobrevivir.", true),
    Pregunta("El desierto del Sahara es el más grande del mundo.", true),
    Pregunta("Los flamencos son rosas debido a su dieta.", true),
    Pregunta("El tiburón ballena es el pez más grande del mundo.", true),
    Pregunta("La Tierra tarda 24 horas en girar sobre su eje.", true),
    Pregunta("Los perros tienen un sentido del olfato más desarrollado que los humanos.", true),
    Pregunta("El Sol es el centro del sistema solar.", true),
    Pregunta("La Vía Láctea es una galaxia.", true),
    Pregunta("El kiwi es una fruta que crece en árboles.", false),
    Pregunta("El caballo de Troya fue un regalo de los espartanos a los troyanos.", false),
    Pregunta("La Torre Eiffel está en Roma.", false),
    Pregunta("El café se cultiva principalmente en climas tropicales.", true),
    Pregunta("La fotosíntesis es un proceso que ocurre en las hojas de las plantas.", true),
    Pregunta("La primera guerra mundial comenzó en 1939.", false),
    Pregunta("Los volcanes expulsan lava.", true),
    Pregunta("El algodón es una fibra natural.", true),
    Pregunta("El mar Muerto es uno de los lugares más bajos de la Tierra.", true),
    Pregunta("La ballena azul es el animal más grande del mundo.", true),
    Pregunta("La Luna emite su propia luz.", false),
    Pregunta("La electricidad estática se genera por el movimiento de electrones.", true),
    Pregunta("El triángulo tiene tres lados.", true),
    Pregunta("El color de la sangre es azul dentro del cuerpo humano.", false),
    Pregunta("Los huracanes se forman en océanos cálidos.", true),
    Pregunta("La capital de España es Barcelona.", false),
    Pregunta("Las estrellas están hechas principalmente de hidrógeno y helio.", true),
    Pregunta("El océano Índico es el más pequeño del mundo.", false),
    Pregunta("Los pandas se alimentan principalmente de bambú.", true),
    Pregunta("El ser humano tiene más de 200 huesos en el cuerpo.", true),
    Pregunta("La cebolla es una raíz.", false),
    Pregunta("Los huracanes giran en sentido horario en el hemisferio norte.", false),
    Pregunta("El idioma oficial de Egipto es el árabe.", true),
    Pregunta("La materia tiene tres estados principales: sólido, líquido y gas.", true),
    Pregunta("Los murciélagos son ciegos.", false),
    Pregunta("El oro se encuentra en la tabla periódica de los elementos.", true),
    Pregunta("El tomate es una fruta.", true),
    Pregunta("El Polo Norte está compuesto de hielo sobre el océano.", true),
    Pregunta("El tiburón blanco es un mamífero.", false),
    Pregunta("La bandera de Brasil tiene un diamante amarillo.", true),
    Pregunta("El ADN humano tiene más de 3 mil millones de pares de bases.", true),
    Pregunta("El bambú puede crecer varios centímetros en un solo día.", true),
    Pregunta("Las arañas tienen ocho patas.", true),
    Pregunta("El agua salada cubre aproximadamente el 50% de la superficie terrestre.", false),
    Pregunta("Los camaleones cambian de color para camuflarse siempre.", false),
    Pregunta("El diamante es una forma cristalina de carbono.", true),
    Pregunta("La lava está más caliente que el agua hirviendo.", true),
    Pregunta("Los aviones comerciales vuelan por encima de 30,000 pies de altura.", true),
    Pregunta("El camello almacena agua en sus jorobas.", false),
    Pregunta("Los tiburones son peces cartilaginosos.", true),
    Pregunta("El arcoíris aparece cuando el agua refracta la luz del sol.", true),
    Pregunta("Los flamencos obtienen su color rosa del betacaroteno en su dieta.", true),
    Pregunta("El pez espada es conocido por su velocidad.", true),
    Pregunta("El oxígeno es el gas más abundante en el aire.", false),
    Pregunta("El ser humano necesita proteínas para construir músculos.", true),
    Pregunta("Las ranas son anfibios.", true),
    Pregunta("El planeta Venus tiene un día más largo que un año.", true),
    Pregunta("Los camellos tienen párpados dobles para proteger sus ojos de la arena.", true),
    Pregunta("El kilómetro es una unidad de tiempo.", false),
    Pregunta("La función principal de los riñones es filtrar la sangre.", true),
    Pregunta("Las estrellas de mar tienen ojos en el extremo de cada brazo.", true),
    Pregunta("Los pájaros descienden de los dinosaurios.", true),
    Pregunta("El hielo seco es dióxido de carbono congelado.", true),
    Pregunta("La trompa de un elefante tiene más de 40,000 músculos.", true),
    Pregunta("Las águilas construyen nidos en el suelo.", false),
    Pregunta("El corazón humano late alrededor de 100,000 veces al día.", true),
    Pregunta("El oso polar tiene la piel negra debajo de su pelaje.", true),
    Pregunta("El tiburón ballena se alimenta de plancton.", true),
    Pregunta("La luna Europa es un satélite de Júpiter.", true),
    Pregunta("El gas helio es más ligero que el aire.", true),
    Pregunta("El primer ser humano en viajar al espacio fue Neil Armstrong.", false),
    Pregunta("Las anguilas eléctricas pueden generar descargas de hasta 600 voltios.", true),
    Pregunta("El símbolo químico del oxígeno es O.", true),
    Pregunta("La velocidad del sonido en el aire es de aproximadamente 343 m/s.", true),
    Pregunta("Los cangrejos pueden regenerar sus pinzas perdidas.", true),
    Pregunta("El chocolate negro tiene más antioxidantes que el chocolate con leche.", true),
    Pregunta("Los planetas gaseosos tienen superficies sólidas.", false),
    Pregunta("El ser humano promedio tiene cinco litros de sangre.", true),
    Pregunta("Las estrellas emiten luz porque están hechas de plasma caliente.", true),
    Pregunta("La electricidad siempre fluye de negativo a positivo.", false),
    Pregunta("Las ballenas orca pertenecen a la familia de los delfines.", true),
    Pregunta("El agua ocupa más espacio al congelarse que en estado líquido.", true),
    Pregunta("El cerebro humano es aproximadamente 60% grasa.", true),
    Pregunta("El sol se encuentra a unos 8 minutos luz de la Tierra.", true),
    Pregunta("Los caballitos de mar son peces.", true),
    Pregunta("El planeta Marte tiene agua en estado líquido en su superficie.", false),
    Pregunta("Las nutrias marinas usan herramientas para abrir conchas.", true),
    Pregunta("El Everest está ubicado en la cordillera del Himalaya.", true),
    Pregunta("Los satélites artificiales giran alrededor de los planetas.", true),
    Pregunta("Las focas son reptiles.", false),
    Pregunta("La fórmula química del agua es H2O.", true),
    Pregunta("Las hormigas son insectos sociales.", true),
    Pregunta("El arco iris tiene colores en el orden inverso al de la luz dispersada.", false),
    Pregunta("El hierro se encuentra en la sangre en forma de hemoglobina.", true),
    Pregunta("El piano tiene más cuerdas que un violín.", true),
    Pregunta("Los elefantes africanos tienen orejas más grandes que los asiáticos.", true),
    Pregunta("El planeta más cercano al Sol es Mercurio.", true),
    Pregunta("El agua de mar es más salada que el agua dulce.", true)
    )